version: '3.8'

services:
  selcoool_nestjs:
    container_name: selcoool_nestjs
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - root_rent_room_network
    env_file:
      - .env

networks:
  root_rent_room_network:
    external: true




# services:
#   selcoool_nestjs:
#     container_name: selcoool_nestjs
#     restart: always
#     build:
#       context: ./
#     networks:
#       - root_rent_room_network
#     env_file:
#       - .env

# networks:
#   root_rent_room_network:
#     external: true



# services:
#   selcoool_nestjs:
#     container_name: selcoool_nestjs
#     restart: always
#     build:
#       context: ./
#     networks:
#       - root_rent_room_network
#     env_file:
#       - .env

# networks:
#   root_rent_room_network:
#     external: true

