# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to VPS BACKEND_04022231z

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to VPS and update project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}  # Sử dụng nếu bạn dùng mật khẩu cho SSH
        script: |
          echo "Checking if the project directory exists..."
          if [ -d "/root/selcoool_nestjs" ]; then
            echo "Thư mục dự án tồn tại"
            cd /root/selcoool_nestjs

            git pull
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d --build || docker-compose logs
            # Optional: Only prune if required
            # docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx
          else
            echo "Thư mục dự án không tồn tại"
            mkdir -p /root/selcoool_nestjs
            cd /root/selcoool_nestjs

            git clone https://github.com/${{ github.repository }} /root/selcoool_nestjs
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d || docker-compose logs
            # Optional: Only prune if required
            # docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx
          fi
          echo "Cập nhật API project_nestjs hoàn thành

        # script: |
        #   echo "Xoa thu muc du an"
        #   rm -rf /root/project_nestjs
        #   echo "Xoa images and container"
          
        #   docker stop $(docker ps -aq) || true
        #   docker rm $(docker ps -aq) || true
        #   docker rmi $(docker images -q) || true
        #   docker-compose -f docker-compose-api-project_nestjs.yml down
        #   docker system prune -a -f
        #   sudo systemctl restart docker
        #   echo "Xoa du an 1"





