name: Deploy to VPS BACKEND_040222311

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to VPS and update project
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Checking if the project directory exists..."
          if [ -d "/root/selcoool_nestjs" ]; then
            echo "Thư mục dự án tồn tại"
            cd /root/selcoool_nestjs

            git pull
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d --build || docker-compose logs
            # Optional: Only prune if required
            # docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx
          else
            echo "Thư mục dự án không tồn tại"
            mkdir -p /root/selcoool_nestjs
            cd /root/selcoool_nestjs

            git clone https://github.com/${{ github.repository }} /root/selcoool_nestjs
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d || docker-compose logs
            # Optional: Only prune if required
            # docker system prune -f
            # Restart Nginx
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx
          fi
          echo "Cập nhật API project_nestjs hoàn thành"





# name: Deploy to VPS BACKEND_040222311

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     timeout-minutes: 20
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: SSH to VPS and update project
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.VPS_IP }}
#         username: ${{ secrets.VPS_USERNAME }}
#         password: ${{ secrets.VPS_PASSWORD }}  # Sử dụng nếu bạn dùng mật khẩu cho SSH
#         script: |
#           echo "Checking if the project directory exists..."
#           if [ -d "/root/selcoool_nestjs" ]; then
#             echo "Tồn tại thư mục dự án"
#             cd /root/selcoool_nestjs

#             git pull
#             docker-compose -f docker-compose-selcoool_nestjs.yml up -d --build --timeout 3000
#             docker system prune -f
#             # Restart Nginx
#             cd ~
#             docker-compose -f docker-compose-nginx.yml restart nginx
#           else
#             echo "Không hề tồn tại thư mục dự án"
#             mkdir -p /root/project_nestjs
#             cd /root/project_nestjs

#             git clone https://github.com/${{ github.repository }} /root/selcoool_nestjs
#             docker-compose -f docker-compose-selcoool_nestjs.yml up -d --timeout 3000
#             docker system prune -f
#             # Restart Nginx
#             cd ~
#             docker-compose -f docker-compose-nginx.yml restart nginx
#           fi
#           echo "Hoàn thành công việc update API project_nestjs. Chúc mừng bạn đã hoàn thành"

        # script: |
        #   echo "Xoa thu muc du an"
        #   rm -rf /root/project_nestjs
        #   echo "Xoa images and container"
          
        #   docker stop $(docker ps -aq) || true
        #   docker rm $(docker ps -aq) || true
        #   docker rmi $(docker images -q) || true
        #   docker-compose -f docker-compose-api-project_nestjs.yml down
        #   docker system prune -a -f
        #   sudo systemctl restart docker
        #   echo "Xoa du an 1"





