# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to VPS BACKEND_0402223

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH to VPS and update project
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}  # Use if you authenticate with a password
        # Alternatively, use SSH_PRIVATE_KEY for better security:
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Checking if the project directory exists..."
          if [ -d "/root/selcoool_nestjs" ]; then
            echo "Project directory exists"
            cd /root/selcoool_nestjs

            echo "Pulling latest changes..."
            git pull

            echo "Attempting to build Docker image..."
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d --build || {
              echo "Failed to build the Docker image, showing logs:";
              docker-compose -f docker-compose-selcoool_nestjs.yml logs;
              exit 1;
            }

            echo "Restarting Nginx..."
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx || {
              echo "Failed to restart Nginx, check Nginx logs for more details";
              exit 1;
            }
          else
            echo "Project directory does not exist, setting up for the first time"
            mkdir -p /root/selcoool_nestjs
            cd /root/selcoool_nestjs

            echo "Cloning repository..."
            git clone https://github.com/${{ github.repository }} /root/selcoool_nestjs

            if [ ! -f "/root/selcoool_nestjs/.env" ]; then
              echo "Creating default .env file"
              echo "DATABASE_URL=your_database_url_here" > /root/selcoool_nestjs/.env
            fi

            echo "Building Docker image for the first time..."
            docker-compose -f docker-compose-selcoool_nestjs.yml up -d || {
              echo "Failed to build Docker image on first-time setup";
              docker-compose -f docker-compose-selcoool_nestjs.yml logs;
              exit 1;
            }

            echo "Restarting Nginx..."
            cd ~
            docker-compose -f docker-compose-nginx.yml restart nginx || {
              echo "Failed to restart Nginx on first-time setup";
              exit 1;
            }
          fi
          echo "Deployment complete"



        # script: |
        #   echo "Xoa thu muc du an"
        #   rm -rf /root/project_nestjs
        #   echo "Xoa images and container"
          
        #   docker stop $(docker ps -aq) || true
        #   docker rm $(docker ps -aq) || true
        #   docker rmi $(docker images -q) || true
        #   docker-compose -f docker-compose-api-project_nestjs.yml down
        #   docker system prune -a -f
        #   sudo systemctl restart docker
        #   echo "Xoa du an 1"





